### ISSUE TITLE
Does not work in streaming mode

### ISSUE THREAD

**Issue by morpheus2448** [shaunabanana/llama.py#1]
HI,

I ran this with the latest version of llama.cpp using the example code:

```python
if __name__ == '__main__':
    for token in llama(
        'Below is a conversation between a user and LLaMA:\nUser: Hello!\nLLaMA: Hi! I am LLaMA, a large language model.\nUser:', 
        skip_prompt=False,
        executable='./main',
       model='/home/somedir/ggml-model-gptq4.bin',
        threads=12,
        interactive=True,
    ):
        print(token, end='', flush=True)
```

The model loads and the prompt is passed to the model, but no additional tokens are generated (the CPU is only being loaded as prompt tokens are fed to model).

If I change interactive to False, the model is happy to generate many tokens.

**Comment by shaunabanana** [comment]
Hi @morpheus2448 ! 

I originally wrote this script as a makeshift solution before a proper binding came out, and since there are projects like [llama-cpp-python](https://github.com/abetlen/llama-cpp-python) providing working bindings to the latest llama.cpp (which updates faster than I can keep up), I'm no longer planning to maintain this repository and would like to kindly direct you to other solutions. 

Sorry for the confusion and potential time wasted! I will archive this repo and post a notice in the readme as well.
